fix: pass ready to deploy as output for next step

diff --git a/.github/workflows/deploy-to-feature-environment.yml b/.github/workflows/deploy-to-feature-environment.yml
--- a/.github/workflows/deploy-to-feature-environment.yml
+++ b/.github/workflows/deploy-to-feature-environment.yml
@@ -26,10 +26,11 @@ jobs:
   generate_stack_name_and_branch:
     runs-on: ubuntu-24.04
     outputs:
-      slugified_branch: ${{  steps.slugify_bname.outputs.stack  }}
-      branch_name: ${{  steps.set_branch_and_pr_number.outputs.BRANCH_NAME  }}
-      pr_number: ${{  steps.set_branch_and_pr_number.outputs.PR_NUMBER  }}
-      author: ${{  steps.get_author.outputs.AUTHOR  }}
+      ready_to_deploy: ${{ steps.check-labels.outputs.ready_to_deploy }}
+      slugified_branch: ${{ steps.slugify_bname.outputs.stack }}
+      branch_name: ${{ steps.set_branch_and_pr_number.outputs.BRANCH_NAME }}
+      pr_number: ${{ steps.set_branch_and_pr_number.outputs.PR_NUMBER }}
+      author: ${{ steps.get_author.outputs.AUTHOR }}
     steps:
       - uses: actions/checkout@v3
 
@@ -53,13 +54,17 @@ jobs:
           echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
 
       - name: Check for "🚀 Ready to deploy" label
+        id: check-labels
         run: |
           labels=$(gh pr view $PR_NUMBER --json labels --jq '.labels[].name')
-          if [[ "$labels" != *"🚀 Ready to deploy"* ]]; then
-            echo "Label '🚀 Ready to deploy' not found. Exiting."
-            exit 1
-          else
+          if [[ "$labels" == *"🚀 Ready to deploy"* ]]; then
             echo "Label '🚀 Ready to deploy' found. Continuing."
+            echo "ready_to_deploy=true" >> "$GITHUB_ENV"
+            echo "ready_to_deploy=true" >> "$GITHUB_OUTPUT"
+          else
+          echo "Label '🚀 Ready to deploy' not found. Skipping."
+            echo "ready_to_deploy=false" >> "$GITHUB_ENV"
+            echo "ready_to_deploy=false" >> "$GITHUB_OUTPUT"
           fi
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -103,7 +108,7 @@ jobs:
             core.setOutput('stack', slugify('${{ env.BRANCH_NAME }}'));
 
   trigger-build:
-    if: ${{ (github.event_name == 'workflow_dispatch') || (!contains(github.actor, 'bot') && github.event.pull_request.head.repo.fork == false) }}
+    if: ${{ (github.event_name == 'workflow_dispatch') || (!contains(github.actor, 'bot') && github.event.pull_request.head.repo.fork == false && needs.generate_stack_name_and_branch.outputs.ready_to_deploy == 'true') }}
     needs: generate_stack_name_and_branch
     uses: ./.github/workflows/build-images-from-branch.yml
     with:
@@ -111,7 +116,7 @@ jobs:
     secrets: inherit
 
   trigger-e2e:
-    if: ${{ (github.event_name == 'workflow_dispatch') || (!contains(github.actor, 'bot') && github.event.pull_request.head.repo.fork == false && contains(steps.check-labels.outputs.labels, '🚀 Ready to deploy')) }}
+    if: ${{ (github.event_name == 'workflow_dispatch') || (!contains(github.actor, 'bot') && github.event.pull_request.head.repo.fork == false && needs.generate_stack_name_and_branch.outputs.ready_to_deploy == 'true') }}
     runs-on: ubuntu-24.04
     needs: generate_stack_name_and_branch
     environment: ${{  needs.generate_stack_name_and_branch.outputs.slugified_branch  }}
