fix: Allow Skip security scan

diff --git a/.github/workflows/deploy-to-feature-environment.yml b/.github/workflows/deploy-to-feature-environment.yml
--- a/.github/workflows/deploy-to-feature-environment.yml
+++ b/.github/workflows/deploy-to-feature-environment.yml
@@ -150,10 +150,11 @@ jobs:
     uses: ./.github/workflows/build-images-from-branch.yml
     with:
       branch_tag_name: ${{ needs.generate_stack_name_and_branch.outputs.branch_name }}
+      skip_security_check: true
     secrets: inherit
 
   trigger-e2e:
-    if: always() && needs.trigger-build.outputs.build_status == 'success'
+    if: always()
     runs-on: ubuntu-24.04
     needs: [generate_stack_name_and_branch, trigger-build]
     outputs:
@@ -161,7 +162,14 @@ jobs:
       deployment_link: ${{ steps.print-links.outputs.deployment_link }}
     steps:
       - uses: actions/checkout@v3
-
+      - name: Check trigger-build status and exit on non-success
+        run: |
+          if [ ${{ needs.trigger-build.outputs.build_status }} == 'success' ]; then
+            echo "Trigger build completed without issues"
+          else
+            echo "Trigger build job failed"
+            exit 1
+          fi
       - name: Parse the branch name and set it as environment variable
         run: |
           BRANCH_NAME=${{ needs.generate_stack_name_and_branch.outputs.branch_name }}
