require PRs to have 'Ready to deploy' label to be deployed

diff --git a/.github/workflows/deploy-to-feature-environment.yml b/.github/workflows/deploy-to-feature-environment.yml
--- a/.github/workflows/deploy-to-feature-environment.yml
+++ b/.github/workflows/deploy-to-feature-environment.yml
@@ -6,11 +6,11 @@
 # & Healthcare Disclaimer located at http://opencrvs.org/license.
 #
 # Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
-name: Deploy branch & run E2E
+name: Deploy PR to feature environment
 
 on:
   pull_request:
-    types: [opened, synchronize]
+    types: [opened, synchronize, labeled]
   workflow_dispatch:
     inputs:
       pr_number:
@@ -25,37 +25,47 @@ concurrency:
 jobs:
   generate_stack_name_and_branch:
     runs-on: ubuntu-22.04
-    outputs: 
+    outputs:
       slugified_branch: ${{  steps.slugify_bname.outputs.stack  }}
       branch_name: ${{  steps.set_branch_name.outputs.BRANCH_NAME  }}
     steps:
-       - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-       - name: Get branch name (when manually triggered)
-         env:
-           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
-         if: ${{ github.event_name == 'workflow_dispatch' }}
-         run: |
-           PR_NUMBER=${{ github.event.inputs.pr_number }}
-           PR_DATA=$(gh pr view $PR_NUMBER --json headRefName,headRefOid)
-           BRANCH_NAME=$(echo "$PR_DATA" | jq -r '.headRefName')
-           echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
-         
-       
-       - name: Get Branch Name (on PR creation)
-         if: ${{ github.event_name != 'workflow_dispatch' }}
-         run: |
-           echo "BRANCH_NAME=$(echo ${{ github.head_ref }})" >> $GITHUB_ENV
-        
-       - name: Set the branch name as output
-         id: set_branch_name
-         run: |
-           echo "BRANCH_NAME=$(echo ${{  env.BRANCH_NAME  }})" >> $GITHUB_OUTPUT
-           
-       - name: Slugify the branch name
-         id: slugify_bname
-         uses: actions/github-script@v7
-         with:
+      - name: Get branch name (when manually triggered)
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+        if: ${{ github.event_name == 'workflow_dispatch' }}
+        run: |
+          PR_NUMBER=${{ github.event.inputs.pr_number }}
+          PR_DATA=$(gh pr view $PR_NUMBER --json headRefName,headRefOid)
+          BRANCH_NAME=$(echo "$PR_DATA" | jq -r '.headRefName')
+          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
+
+      - name: Check for "🚀 Ready to deploy" label
+        if: ${{ github.event_name != 'workflow_dispatch' }}
+        run: |
+          labels=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
+          if [[ "$labels" != *"🚀 Ready to deploy"* ]]; then
+            echo "Label not found, cancelling workflow."
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Get Branch Name (on PR creation)
+        if: ${{ github.event_name != 'workflow_dispatch' }}
+        run: |
+          echo "BRANCH_NAME=$(echo ${{ github.head_ref }})" >> $GITHUB_ENV
+
+      - name: Set the branch name as output
+        id: set_branch_name
+        run: |
+          echo "BRANCH_NAME=$(echo ${{  env.BRANCH_NAME  }})" >> $GITHUB_OUTPUT
+
+      - name: Slugify the branch name
+        id: slugify_bname
+        uses: actions/github-script@v7
+        with:
           script: |
             function slugify(str) {
               return str
@@ -68,8 +78,6 @@ jobs:
                 .replace(/[^a-zA-Z0-9]+$/g, '');
             }
             core.setOutput('stack', slugify('${{ env.BRANCH_NAME }}'));
-
-           
 
   trigger-e2e:
     if: ${{ !contains(github.actor, 'bot') && github.event.pull_request.head.repo.fork == false }}
@@ -119,7 +127,7 @@ jobs:
           echo "PR Branch: ${{ env.BRANCH_NAME }}"
           echo "PR Head Commit Hash: ${{ env.HEAD_COMMIT_HASH }}"
           echo "Farajaland Commit Hash: ${{ env.FARAJALAND_COMMIT_HASH }}"
-      
+
       - name: Parse the stack name
         id: generate_stack
         run: |
@@ -143,7 +151,7 @@ jobs:
               }
             });
 
-            
+
 
             console.log(result);
             await new Promise(resolve => setTimeout(resolve, 10000));
